package com.example.bug_venture_app;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import java.util.ArrayList;
import java.util.List;

public class Ques_Sit_Helper extends SQLiteOpenHelper{

    private Context context;
    private static final String DB_NAME = "Sit_questions.db";
    private static final int DB_VERSION = 3;
    private static final String TABLE_NAME = "Quiz_Question";
    private static final String UID = "_UID";
    private static final String QUESTION = "QUESTION";

    private static final String CREATE_TABLE = "CREATE TABLE " + TABLE_NAME + " ( " + UID + " INTEGER PRIMARY KEY AUTOINCREMENT , " + QUESTION + " VARCHAR(255));";
    private static final String DROP_TABLE = "DROP TABLE IF EXISTS " + TABLE_NAME;

    Ques_Sit_Helper(Context context) {
        super(context, DB_NAME, null, DB_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {
        sqLiteDatabase.execSQL(CREATE_TABLE);
    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int j) {
        sqLiteDatabase.execSQL(DROP_TABLE);
        onCreate(sqLiteDatabase);
    }

    void allQuestion() {
        ArrayList<QuizQuestionSit> arraylist = new ArrayList<>();

        arraylist.add(new QuizQuestionSit("Who is Larry Pressler ?"));



        arraylist.add(new QuizQuestionSit("Crime: Kill a person in a market who has bodyguards dressed as civilians with the help of a lethal injection. It must be recorded by the wife and the murder is to be done by the husband.\n" +
                "\n" +
                "Only 2 days are left and there is no lead from Detective Pradyuman.\n"));
        arraylist.add(new QuizQuestionSit("Question")); //2



        arraylist.add(new QuizQuestionSit("Right before the injection was to be injected, husband notices one of the bodyguards approaching the wife, because he was recording the victim.\n" +
                "\n" +
                "As Mahesh Verma, what will you choose?\n"));
        arraylist.add(new QuizQuestionSit("There is still no lead from the detective and the deadline has passed.\n" +
                "There is another parcel received from the angry kidnapper with blood soaked clothes of the child and a warning which says that the next task is due tomorrow and if it is not accomplished then the next parcel will have the child’s corpse.\n" +
                "The detective suggests that for this task, instead of committing the crime for real, you can talk to the target and convince him to help them by being a part of a play where he acts to be killed by the couple for the video. But the detective also warns that there might be eyes following you and there is a very high risk\n"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));//4


        arraylist.add(new QuizQuestionSit("When guards confront Mrs. Pooja Verma, she says that she was recording her husband and not the person and he is saved. They finally abort the mission and get home safely.\n" +
                "There is another parcel received from the angry kidnapper with blood soaked clothes of Ria and a warning which says that the next task is due tomorrow and if it is not accomplished then the next parcel will have Ria’s corpse in it.\n" +
                "\nDetective Pradyuman suggests that for this task, instead of committing the crime for real, you can talk to the target and convince him to help them by being a part of a play where he acts to be killed by the couple for the video. But the detective also warns that there might be eyes following you and there is a very high risk of being noticed by the kidnapper and he might kill Ria.\n" +
                "\n" +
                "As Mr. Verma what will you choose\n"));
        arraylist.add(new QuizQuestionSit("The bodyguards are distracted and the couple make a safe escape with the mission done.\n" +
                " now the video tape is to be left in a trash can for the kidnapper. \n"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));//8

        arraylist.add(new QuizQuestionSit("Parents talk to the victim for orchestrating his fake death, and the crime goes as planned, victim fakes his death and Mrs.Verma successfully records the entire scene. They drop the recording in a trash can nearby as per the kidnapper’s instructions. The detective stays at the crime scene and notices the person who turns up to receive the tape does not have a hand. He asks the Mr. Verma to show his entire patient records as he doubts there is some medical history between him and the kidnapper. But releasing the records can end his career and he can lose his medical license as well as face a sentence for releasing confidential patient records. As Mr.Verma what will you choose?\n"));
        arraylist.add(new QuizQuestionSit("Parents complete the crime as per the instructions of the kidnapper and leave the video tapes in the dustbin. This time detective stays at the crime scene to observe the man who comes to pick up the tapes. He notices that the man who comes to receive the tapes does not have a hand. He asks the Mr. Verma to show his entire patient records as he doubts there is some medical history between him and the kidnapper. But releasing the records can end his career and he can lose his medical license as well as face a sentence for releasing confidential patient records. As Mr.Verma what will you choose?\n"));
        arraylist.add(new QuizQuestionSit("A kid comes to pick the tape and when the detective follows the kid, the kid is pulled into a van and the detective was fired upon by a gun.\n" +
                "The detective is very scared and says that he won’t be able to continue with the job. \n" +
                "While this discussion Another parcel is received from the kidnapper in which there are blood soaked clothes of the child with the next task and a warning that says get rid of the detective and do not act smart or else it will the child’s corpse next time. \n"));
        arraylist.add(new QuizQuestionSit("The kidnapper notices that you are waiting there, so he did not come.\n" +
                "The angry kidnapper sends another parcel which says that now the wife has to kill the husband or else the child is dead.\n"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));//16

        arraylist.add(new QuizQuestionSit("Upon receiving records from the father, Detective Pradyuman notices a similarity between kidnapper and Ria’s grandfather in law. Mr. Pradyuman advices to arrange a fake funeral so that the kidnapper reacts to it somehow. Meanwhile the kidnapper sends another parcel. As Mr.Verma what will you choose?\n"));
        arraylist.add(new QuizQuestionSit("Mr. Pradyuman advices to arrange the fake funeral so that the kidnapper reacts to it somehow. \n" +
                "Meanwhile the kidnapper sends another parcel. As Mr.Verma what will you choose?\n"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("The detective suggests that for this task, instead of committing the crime for real, you can talk to the target and convince him to help them by being a part of a play where he acts to be killed by the couple for the video. But the detective also warns that there might be eyes following you and there is a very high risk\n"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));//32

        arraylist.add(new QuizQuestionSit("Commit the final crime!\n" +
                "\n" +
                "You can either save the father or the kid.As a Mrs. Verma what will you choose?\n"));
        arraylist.add(new QuizQuestionSit("As Mr. Pradyuman had doubts on Ria’s maternal grandfather being the kidnapper so he follows him thinking that by the news of fake funeral he will commit any suspicious move. But while following Ria’s grandfather notices that someone is following him and kills the detective. He gets very frustrated and gives Ria’s mother one final choice - Save Mr.Verma and Ria will be killed or Save Ria and father will have to die.\n" +
                "\n" +
                "As Mrs. Verma what will you choose?\n"));
        arraylist.add(new QuizQuestionSit("Commit the final crime!\n" +
                "\n" +
                "You can either save the father or the kid.As a Mrs. Verma what will you choose?\n"));
        arraylist.add(new QuizQuestionSit("As Mr. Pradyuman had doubts on Ria’s maternal grandfather being the kidnapper so he follows him thinking that by the news of fake funeral he will commit any suspicious move. But while following Ria’s grandfather notices that someone is following him and kills the detective. He gets very frustrated and gives Ria’s mother one final choice - Save Mr.Verma and Ria will be killed or Save Ria and father will have to die.\n" +
                "\n" +
                "As Mrs. Verma what will you choose?\n"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));//64

        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));//128

        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));//256

        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));
        arraylist.add(new QuizQuestionSit("Question"));//512


        this.addAllQuestions(arraylist);
    }

    private void addAllQuestions(ArrayList<QuizQuestionSit> allQuestions) {
        SQLiteDatabase db = this.getWritableDatabase();
        db.beginTransaction();
        try {
            ContentValues values = new ContentValues();
            for(QuizQuestionSit question : allQuestions) {
                values.put(QUESTION, question.getQuestion());
                db.insert(TABLE_NAME, null, values);
            }
            db.setTransactionSuccessful();
        } finally {
            db.endTransaction();
            db.close();
        }
    }

    List<QuizQuestionSit> getAllOfTheQuestions() {
        List<QuizQuestionSit> questionList = new ArrayList<>();
        SQLiteDatabase db = this.getWritableDatabase();
        db.beginTransaction();
        String[] column = {UID, QUESTION};
        Cursor cursor = db.query(TABLE_NAME, column, null, null, null, null, null);

        while (cursor.moveToNext()) {
            QuizQuestionSit question = new QuizQuestionSit();
            question.setId(cursor.getInt(0));
            question.setQuestion(cursor.getString(1));
            questionList.add(question);
        }

        db.setTransactionSuccessful();
        db.endTransaction();
        cursor.close();
        db.close();
        return questionList;
    }
}
